version: 0.1.{build}

environment:
  DOCKER_USER:
    secure: 6rLbbyBh1nQI1gXYMVTBsA==
  DOCKER_PASS:
    secure: OsNZXzHcyFIcG3e2jJ9j+w==

pull_requests:
  do_not_increment_build_number: true

image: Ubuntu1804

build_script:
- ps: docker build -t carlosvicente/configuration-store .

test: off

deploy_script:
- ps: >-
    "$env:DOCKER_PASS" | docker login --username "$env:DOCKER_USER" --password-stdin


    docker push $env:DOCKER_USER/configuration-store:latest