# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
    - image: golang:1.11.1-stretch
    working_directory: /workspace/src/configuration-store
    steps:
    - checkout
    - run:
        name: Setup Environment Variables
        command: |
          echo 'export GOPATH="$GOPATH:/workspace"' >> $BASH_ENV
    - run:
        name: Install dependencies manager
        command: |
          go get -u github.com/golang/dep/cmd/dep
    - run:
        name: Get dependencies
        command: |
          dep ensure

    - run:
        name: Test application
        command: |
          go test -v
  deploy:
    docker:
    - image: buildpack-deps:trusty
    steps:
    - checkout
    - run:
        name: Deploy $CIRCLE_BRANCH to Heroku
        command: |
          git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git $CIRCLE_BRANCH:master
