# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
    - image: golang:1.11.1-stretch
    working_directory: /workspace/src/configuration-store
    steps:
    - checkout
    - run:
        name: Setup Environment Variables
        command: |
          echo 'export GOPATH="$GOPATH:/workspace"' >> $BASH_ENV
    - run:
        name: Install dependencies manager
        command: |
          go get -u github.com/golang/dep/cmd/dep
    - run:
        name: Get dependencies
        command: |
          dep ensure
    - run:
        name: ls github
        command: |
          ls /go/src/github.com -la

    - run:
        name: ls vendor
        command: |
          ls ./vendor -la

    - run:
        name: ls work
        command: |
          ls /workspace/src/configuration-store -la

    - run:
        name: Test application
        command: |
          go test -v

    - setup_remote_docker

    - run:
        name: Build docker image
        command: |
          docker build -t configuration-store .
