# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
    - image: golang:1.11.1-stretch
    working_directory: /workspace/src/configuration-store
    steps:
    - checkout
    - run:
        name: Setup Environment Variables
        command: |
          echo 'export GOPATH="$GOPATH:/workspace"' >> $BASH_ENV
    - run:
        name: Install dependencies manager
        command: |
          go get -u github.com/golang/dep/cmd/dep
    - run:
        name: Get dependencies
        command: |
          dep ensure

    - run:
        name: Test application
        command: |
          go test -v

    - setup_remote_docker

    - run:
        name: Install Docker client
        command: |
          set -x
          VER="18.06.1-ce"
          curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
          tar -xz -C /tmp -f /tmp/docker-$VER.tgz
          mv /tmp/docker/* /usr/bin

    - run:
        name: Build docker image
        command: |
          docker build -t configuration-store .

    - run:
        name: Deploy to heroku
        command: |
          docker login --username=$HEROKU_LOGIN --password=$HEROKU_PASS $HEROKU_REGISTRY
          docker tag configuration-store $HEROKU_REGISTRY/$HEROKU_APP_NAME/web
          docker push $HEROKU_REGISTRY/$HEROKU_APP_NAME/web
